#!/usr/bin/env bash
# openclaw-setup.sh — Fix the ROS 2 environment for OpenClaw's gateway service
#
# Problem: OpenClaw's gateway runs as a systemd service with a fixed PATH that
# does not include /opt/ros/<distro>/bin. Any bash command the agent runs is
# in a ROS-blind shell — ros2 commands fail with "command not found".
#
# Fix: Create a systemd drop-in that injects the ROS 2 environment into the
# gateway service. The drop-in survives openclaw updates (which regenerate the
# base service file).
#
# Usage:
#   chmod +x openclaw-setup.sh
#   ./openclaw-setup.sh
#
# Requirements: ROS 2 must already be installed and sourced before running this.

set -euo pipefail

# ── Detect ROS 2 distro ──────────────────────────────────────────────────────
if [ -z "${ROS_DISTRO:-}" ]; then
  echo "ERROR: ROS_DISTRO is not set. Source your ROS 2 environment first:"
  echo "  source /opt/ros/humble/setup.bash"
  exit 1
fi

ROS_ROOT="/opt/ros/$ROS_DISTRO"

if [ ! -f "$ROS_ROOT/setup.bash" ]; then
  echo "ERROR: ROS 2 not found at $ROS_ROOT"
  exit 1
fi

echo "Detected ROS 2 distro: $ROS_DISTRO (at $ROS_ROOT)"

# ── Source ROS 2 to read the actual env values ────────────────────────────────
# shellcheck disable=SC1091
source "$ROS_ROOT/setup.bash"

PYTHON_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")

# ── Locate the openclaw service file ─────────────────────────────────────────
USER_SERVICE="$HOME/.config/systemd/user/openclaw-gateway.service"
SYSTEM_SERVICE="/etc/systemd/system/openclaw-gateway.service"

if [ -f "$USER_SERVICE" ]; then
  SERVICE_KIND="user"
  DROP_IN_DIR="$HOME/.config/systemd/user/openclaw-gateway.service.d"
elif [ -f "$SYSTEM_SERVICE" ]; then
  SERVICE_KIND="system"
  DROP_IN_DIR="/etc/systemd/system/openclaw-gateway.service.d"
else
  echo "ERROR: openclaw-gateway.service not found."
  echo "Make sure openclaw is installed and the gateway service is set up:"
  echo "  openclaw gateway install"
  exit 1
fi

echo "Found $SERVICE_KIND-level openclaw service."
echo "Writing drop-in to: $DROP_IN_DIR/ros-env.conf"

# ── Create drop-in directory ──────────────────────────────────────────────────
if [ "$SERVICE_KIND" = "system" ]; then
  sudo mkdir -p "$DROP_IN_DIR"
else
  mkdir -p "$DROP_IN_DIR"
fi

# ── Build the drop-in content ─────────────────────────────────────────────────
DROPIN_CONTENT="# ROS 2 environment for OpenClaw gateway
# Generated by openclaw-setup.sh — re-run to update after changing ROS distro.
# This drop-in persists across openclaw updates.

[Service]
Environment=ROS_DISTRO=$ROS_DISTRO
Environment=ROS_VERSION=${ROS_VERSION:-2}
Environment=ROS_PYTHON_VERSION=${ROS_PYTHON_VERSION:-3}
Environment=ROS_LOCALHOST_ONLY=${ROS_LOCALHOST_ONLY:-0}
Environment=AMENT_PREFIX_PATH=$ROS_ROOT
Environment=PYTHONPATH=$ROS_ROOT/lib/python${PYTHON_VER}/site-packages:$ROS_ROOT/local/lib/python${PYTHON_VER}/dist-packages
Environment=LD_LIBRARY_PATH=$ROS_ROOT/lib/$(uname -m)-linux-gnu:$ROS_ROOT/lib
"

# Prepend ROS bin to PATH — extract current PATH from the running service if possible,
# otherwise fall back to a sensible default.
RUNNING_PID=$(systemctl ${SERVICE_KIND:+"--$SERVICE_KIND"} show openclaw-gateway --property=MainPID --value 2>/dev/null || echo "")
if [ -n "$RUNNING_PID" ] && [ "$RUNNING_PID" != "0" ] && [ -f "/proc/$RUNNING_PID/environ" ]; then
  CURRENT_PATH=$(cat "/proc/$RUNNING_PID/environ" | tr '\0' '\n' | grep "^PATH=" | cut -d= -f2-)
else
  CURRENT_PATH="/home/$USER/.local/bin:/usr/local/bin:/usr/bin:/bin"
fi
DROPIN_CONTENT+="Environment=PATH=$ROS_ROOT/bin:$CURRENT_PATH
"

# ── Write the drop-in ─────────────────────────────────────────────────────────
if [ "$SERVICE_KIND" = "system" ]; then
  echo "$DROPIN_CONTENT" | sudo tee "$DROP_IN_DIR/ros-env.conf" > /dev/null
else
  echo "$DROPIN_CONTENT" > "$DROP_IN_DIR/ros-env.conf"
fi

echo "Drop-in written."

# ── Reload and restart the service ───────────────────────────────────────────
echo "Reloading systemd and restarting openclaw-gateway..."
if [ "$SERVICE_KIND" = "system" ]; then
  sudo systemctl daemon-reload
  sudo systemctl restart openclaw-gateway
  ACTIVE=$(sudo systemctl is-active openclaw-gateway 2>/dev/null || echo "unknown")
else
  systemctl --user daemon-reload
  systemctl --user restart openclaw-gateway
  ACTIVE=$(systemctl --user is-active openclaw-gateway 2>/dev/null || echo "unknown")
fi

echo "Service status: $ACTIVE"

# ── Verify ───────────────────────────────────────────────────────────────────
RUNNING_PID=$(systemctl ${SERVICE_KIND:+"--$SERVICE_KIND"} show openclaw-gateway --property=MainPID --value 2>/dev/null || echo "")
if [ -n "$RUNNING_PID" ] && [ "$RUNNING_PID" != "0" ]; then
  DETECTED=$(cat "/proc/$RUNNING_PID/environ" 2>/dev/null | tr '\0' '\n' | grep "^ROS_DISTRO=" || echo "")
  if [ -n "$DETECTED" ]; then
    echo "✓ Verified: gateway process has $DETECTED"
  else
    echo "⚠ Could not verify env in running process — check manually:"
    echo "  cat /proc/$RUNNING_PID/environ | tr '\\0' '\\n' | grep ROS"
  fi
fi

echo ""
echo "Done. The openclaw agent can now run ros2 commands without sourcing manually."
echo "If you change your ROS distro, re-run this script."
